const places = [
  "Nanyang Technological University Singapore Singapore Singapore",
  "Institute for Technology & Society (ITS) Rio de Janeiro Brazil",
  "ERIA: Economic Research Institute for ASEAN and East Asia Senayan Indonesia",
  "Tech For Good Institute Singapore Singapore",
  "Regional Center for Studies on the Development of the Information Society (CETIC) Saõ Paulo Brazil",
  "Hiperderecho Lima Peru",
  "Asociación por los Derechos Civiles (ADC) Buenos Aires Argentina",
  "Desinformante Saõ Paulo Brazil",
  "El Veinte Bogota Colombia",
  "PROLEDI (Programa Derecho a la Libertad de Expresión de la Universidad de Costa Rica) San José Costa Rica",
  "De La Salle University Manila Philippines",
  "Shorenstein Center Harvard Kennedy School Cambridge United States",
  "Journalism and Media Studies Centre - Hong Kong University Pok Fu Lam, Hong Kong China",
  "Foundation for Media Alternatives Quezon City Philippines",
  "Department of Government Studies Diponegoro University  Semarang Indonesia",
  "Communication Science Department University of Gadjah Mada Yogyakarta  Indonesia",
  "Capacity Equals Development Africa DAKAR Senegal",
  "Institute of Knowledge Societies  India",
  "Myanmar ICT for Development Organization (MIDO)  Myanmar",
  "School of International Communications The University of Nottingham Ningbo China",
  "Centre of Excellence for Automated Decision-Making and Society (ARC) Brisbane Australia",
  "Open Observatory of Network Interference (OONI) Rome Italy",
  "Columbia Global Freedom of Expression New York United States",
  "UNESCO Institute for Information Technologies in Education Moscow Russian Federation",
  "SINAR Project Subang Jaya Malaysia",
  "ADISI-Cameroun Douala Cameroon",
  "CSIRO's Data61 Sydney Australia",
  "Observatorio de la Desinformación - Uni Complutense Madrid Spain",
  "IDEA Corp inc Marikina City Philippines",
  "Digital Literacy Initiative (DLI)  Uganda",
  "Open Net Seoul Korea, Republic of",
  "Association of Technology, Education, Development, Research and Communication (TEDIC) Asuncion Paraguay",
  "Kenya ICT Action Network (KICTANet) Nairobi Kenya",
  "University of Massachusetts Amherst Amherst United States",
  "Curtin University: Digital Transformation Research Unit Perth Australia",
  "University of Western Australia Tech & Policy Lab Perth  Australia",
  "Tech Policy Design Centre, Australian National University Canberra Australia",
  "Maxim Institute Auckland  New Zealand",
  "FIBRE FALE Auckland New Zealand",
  "Toda Peace Institute Tokyo  Japan",
  "Sciences Po CEVIPOF Research Paris France",
  "Centre for International Governance Innovation (CIGI) Waterloo Canada",
  "Article 19 London  United Kingdom",
  "The Coalition for Independent Technology Research New York United States",
  "Carnegie Endowment for International Peace Washington United States",
  "Integrity Institute washington United States",
  "Democracy Reporting International Berlin Germany",
  "Our World in Data - Global Change Data Lab Oxford United Kingdom",
  "ISTC-CNR, Institute for Cognitive Sciences and Technologies del CNR  Italy",
  "Institute for Strategic Dialogue (ISD) London United Kingdom",
  "International Panel on the Information Environment (IPIE) Zurich Switzerland",
  "Global Network Initiative Washington United States",
  "Council on Tech and Social Cohesion (CTSC)  United States",
  "Forum on Information and Democracy (FID) Paris France",
  "United Nations Human Rights  Switzerland",
  "Digital Action Dublin Ireland",
  "Center for AI and Digital Policy Washington United States",
  "data privacy BR São Paulo Brazil",
  "Ibict - Instituto Brasileiro de Informação em Ciência e Tecnologia Brasília Brazil",
  "Tata STRIVE Mumbai India",
  "International Association for Media and Communication Research (IAMCR) Praha Czech Republic",
  "The International Digital Policy Lab  Australia",
  "Innovation 4 Policy Foundation Kigali Rwanda",
  "Research ICT Africa Cape Town South Africa",
  "TESaCo Paris France",
  "IT for Change Bengaluru India",
  "Access to Knowledge for Development Center (A2K4D) Cairo Egypt",
  "Alexander von Humboldt Institute for Internet and Society (HIIG) Berlin Germany",
  "Berkman Klein Center for Internet & Society Cambridge United States",
  "Syntagma Madrid Spain",
  "Center for Advanced Internet Studies (CAIS) Bochum Germany",
  "Center for Cyber Law & Policy (CCLP) Israel Israel",
  "Center for Information Technology & Society (CITS) Santa Barbara United States",
  "Swedish Law and Informatics Research Institute (IRI), Stockholm University Stockhold Sweden",
  "Center for Media, Data and Society (CMDS) Budapest Hungary",
  "Demos London United Kingdom",
  "Center for Studies on Freedom of Expression and Access to Information Buenos Aires Argentina",
  "Cyberlaw Research Centre (CIJIC) Lisboa Portugal",
  "Central European Digital Media Observatory Prague Czech Republic",
  "Centre de Recherche en Droit Public Montreal Canada",
  "Centre for Communication and Computing Copenhagen Denmark",
  "Centro de Tecnologia y Sociedad Buenos Aires Argentina",
  "Centre for Internet, Smartphone and Society, Bangladesh (CISS-BD) Dhaka Bangladesh",
  "Centro Latam Digital Mexico City Mexico",
  "Digital Law Center (DLC) Geneva Switzerland",
  "Digital Ethnography Research Centre (DEC) Melbourne Australia",
  "Digital Life Initiative (DLI) New York City United States",
  "Düsseldorf Institute for Competition Economics (DICE) Düsseldorf Germany",
  "LIRNEasia Colombo Sri Lanka",
  "Nobeah Foundation Nairobi Kenya",
  "Global Partners Digital  United Kingdom",
  "Internetlab São Paulo Brazil",
  "Institute for Internet Policy & Law (IIPL) Beijing China",
  "Institute for Studies on Artificial Intelligence and Law Beijing China",
  "Institute of Network Cultures Amsterdam Netherlands",
  "Intellectual Property Institute (IPI) Ljubljana Slovenia",
  "Interdepartmental Centre for Research in the History, Philosophy and Sociology of Law, and in Legal Informatics Bologna Italy",
  "Internet Interdisciplinary Institute (IN3) Castelldefels Spain",
  "Regional Center for Studies on the Development of the Information Society (Cetic.br) Cambridge Brazil",
  "Laboratory for Internet Studies (LINIS) St. Petersburg Russian Federation",
  "Legal Tech Lab Helsinki Finland",
  "Nexa Center for Internet & Society, Politecnico di Torino Torino Italy",
  "United Nations University Institute on Computing and Society Macau China",
  "National Secretariat for Media Reforms (NSMR) Nugegoda Sri Lanka",
  "Observatorio de Derecho Informatico Argentino (O.D.I.A.)  Argentina",
  "Research Centre in Information, Law and Society Of the University of Namur (CRIDS) Namur Belgium",
  "Stanford Cyber Policy Center  United States",
  "The New Research on Digital Societies (NeRDS group) Warszawa Poland",
  "Singapore Internet Research Centre Singapore Singapore",
  "Tilburg Institute for Law, Technology, and Society Tilburg Netherlands",
  "The Northumbria Internet & Society Research Interest Group (NINSO) Newcastle United Kingdom",
  "University of Helsinki Legal Tech Lab Helsinki Finland",
  "Vietnam Program for Internet & Society (VPIS) Hanoi Viet Nam",
  "Digital Technologies Policy Laboratory London United Kingdom",
  "Arab World Internet Institute Tunis Tunisia",
  "E-Governance and Internet Governance Foundation for Africa (EGIGFA) Accra Ghana",
  "Bavarian Research Institute for Digital Transformation (bidt) Munich Germany",
  "Center for Information Technology, Society, and Law (ITSL) Zürich Switzerland",
  "Center for Internet Studies and Digital Life Pamplona Spain",
  "Center for Studies on Freedom of Expression and Access to Information (CELEUP) Buenos Aires Argentina",
  "Centre for Law, Technology and Society Ottawa Canada",
  "Innovation and Technology Law Lab Padova Italy",
  "Centre for Computing and Social Responsibility Leicester United Kingdom",
  "Centre Internet et Société du CNRS / Center for Internet and Society of CNRS (CIS-CNRS) Paris France",
  "Centro de Internet y Sociedad – Universidad del Rosario (ISUR) Bogota Colombia",
  "Derechos Digitales Santiago de Chile Chile",
  "Governance and Innovation Program at MBR School of Government  United Arab Emirates",
  "Institute for Information Law (IVIR) Amsterdam Netherlands",
  "Institute for Information, Telecommunication and Media Law (ITM) Münster Germany",
  "Grupo de Investigación sobre Uruguay Sociedad e Internet (GIUSI) Montevideo Uruguay",
  "Manushya Foundation ♾ #WeAreManushyan Phaya Thai Thailand",
  "Haifa Center for Law & Technology Haifa Israel",
  "Human Rights, Big Data and Technology Essex United Kingdom",
  "International Laboratory for Information Technology and Intellectual Property Law St. Petersburg Russian Federation",
  "KU Leuven Centre for IT & IP Law (CiTiP) Leuven Belgium",
  "Internet Policy project group (POLI)  Germany",
  "Radical Xchange (French Chapter) Paris France",
  "University of Houston Law Center Houston United States",
  "Keio International Project for Internet & Society Fujisawa Japan",
  "MIT Center for Civic Media Cambridge United States",
  "Nordic Centre for Internet and Society Oslo Norway",
  "Media Change & Innovation Division, IPMZ zurich Switzerland",
  "Centre for Media Pluralism and Media Freedom (CMPF) Florence Italy",
  "The Governance Lab New York United States",
  "InternetLab - human rights and internet policy think tank São Paulo Brazil",
  "Quello Center, Michigan State University East Lansing United States",
  "Oxford Internet Institute (OII) Oxford United Kingdom",
  "Public Data Lab London United Kingdom",
  "Swedish Law and Informatics Research Institute (IRI)  Sweden",
  "The Center for Technology & Society (CTS) Rio de Janeiro Brazil",
  "Weizenbaum Institute for the Networked Society Berlin Germany",
  "AMIC (Asian Media Information and Communication Centre) Manila Philippines",
  "International Digital Policy Lab Melbourne Australia",
  "Digital Rights Foundation  Pakistan",
  "Center for Advanced Research in Global Communication (CARGC) Philadelphia United States",
  "CNRS Paris France",
  "Movilizatorio Bogotá Colombia",
  "European External Action Service Brussels Belgium",
  "#Leplusimportant Paris France",
  "Center for Countering Digital Hate London United Kingdom",
  "Oxford University’s Programme on Democracy & Technology Oxford United Kingdom",
  "International Institute for Ethical Governance and Accountability (IIEGA) Johannesburg  South Africa",
  "University of Oslo Oslo Norway",
  "Institute for Accountability in the Digital Age  Netherlands",
  "Center for Law & Technology Seoul Korea, Republic of",
  "Center on Science & Technology Policy at Duke University Durham, NC United States",
  "Centre for Communication Governance at National Law University Delhi (CCG) New Delhi India",
  "Centre for Computing and Social Responsibility Leicester United Kingdom",
  "Centre for Internet & Society (CIS) Bangalore India",
  "Centre for the Study of Existential Risk Cambridge United Kingdom",
  "Department of Innovation and Digitalisation in Law Vienna Austria",
  "DiploFoundation Geneva Switzerland",
  "Digital Planet, an interdisciplinary research initiative of The Fletcher School’s Institute Medford United States",
  "Digital Asia Hub (DAH) Hong Kong Island Hong Kong",
  "Centro de Ensino e Pesquisa em Inovação (GEPI) Rio de Janeiro Brazil",
  "Elliott School of International Affairs Washington United States",
  "Global Network of Internet & Society Centers (NoC)  United States",
  "Hans-Bredow-Institut Hamburg Germany",
  "Information Society Project at Yale Law School New Haven United States",
  "IT Law Institute at Istanbul Bilgi University İstanbul Turkey",
  "International Center for Ethics in the Sciences and Humanities (IZEW) Tuebingen Germany",
  "Internet Policy project group (POLI) at Berlin Social Science Center (WZB) Berlin Germany",
  "Institute for Research on Internet & Society (IRIS) Belo Horizonte Brazil",
  "Keio International Project for Internet & Society, Keio University, Tokyo Tokyo Japan",
  "Linterna Verde (LV) Bogota Colombia",
  "People Interest Technology Africa Kampala Uganda",
  "Oxford Internet Institute (OII), University of Oxford Oxford United Kingdom",
  "Observacom  Uruguay",
  "QUT Digital Media Research Centre Brisbane City Australia",
  "SMEX Beirut Lebanon",
  "Strathclyde Centre for Internet Law & Policy Glasgow United Kingdom",
  "Technology & Social Change Group (TASCHA) Seattle United States",
  "Research Group on Law, Science, Technology & Society (LSTS) Brussels Belgium",
  "UMB Data&Society Lab Banská Bystrica Slovakia",
  "Sussex Centre for Information Governance Research Falmer United Kingdom",
  "Unité de droit économique, Centre de droit privé Bruxelles Belgium",
  "Stanford Center for Internet and Society (CIS) Stanford United States",
  "Würzburg Centre for Social and Legal Implications of Artificial Intelligence (SOCAI) Würzburg Germany",
  "Web Science Institute Southampton United Kingdom",
  "Centro de Tecnologia y Sociedad (CETyS) Victoria Argentina",
  "Digital Trade and Data Governance Hub Washington United States",
  "The University of Western Australia Perth Australia",
  "Curtin University Bentley Australia",
  "Otago Polytechnic Auckland International Campus Auckland New Zealand",
  "Tech Policy Design Centre Canberra Australia",
  "Build Up ^ San Francisco United States",
  "Search for Common Ground Washington United States",
  "Neely Center for Ethical Leadership and Decision Making Los Angeles United States",
  "OECD.AI Paris France",
  "BSR San Francisco United States",
  "Portulans Institute Washington D.C. United States",
  "Internet Society Portugal Chapter (ISOCPT) Setúbal Portugal"
]

module.exports = { places }